name: Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    # Build the vite app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      # Create the environment variables from the secrets
      - name: Create environment variables
        run: |
          echo "REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN" >> $GITHUB_ENV
          echo "REACT_APP_AUTH0_CLIENT_ID=$REACT_APP_AUTH0_CLIENT_ID" >> $GITHUB_ENV
      - run: |
          cd client
          npm install
          npm run build
      # Deploy the app to the gh-pages branch